package purchaseordermanagementsystem;

public class Admin_GUI extends javax.swing.JFrame {
    private Administrator admin;
    /**
     * Creates new form Admin_GUI
     */
    public Admin_GUI(Administrator admin) {
        this.admin = admin;
        setTitle("Administrator Menu");
        initComponents();
        getContentPane().setBackground(new java.awt.Color(159, 163, 227));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewAccButton = new javax.swing.JButton();
        RegisterUser = new javax.swing.JButton();
        viewSupplierButton = new javax.swing.JButton();
        viewItemButton = new javax.swing.JButton();
        viewSaleButton = new javax.swing.JButton();
        viewPOButton = new javax.swing.JButton();
        viewPRButton = new javax.swing.JButton();
        ManageUserButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewAccButton.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        viewAccButton.setText("View Personal Account");
        viewAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAccButtonActionPerformed(evt);
            }
        });

        RegisterUser.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        RegisterUser.setText("Register New User");
        RegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUserActionPerformed(evt);
            }
        });

        viewSupplierButton.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        viewSupplierButton.setText("View Supplier List");
        viewSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupplierButtonActionPerformed(evt);
            }
        });

        viewItemButton.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        viewItemButton.setText("View Item List");
        viewItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemButtonActionPerformed(evt);
            }
        });

        viewSaleButton.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        viewSaleButton.setText("View Sale List");
        viewSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSaleButtonActionPerformed(evt);
            }
        });

        viewPOButton.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        viewPOButton.setText("View Purchase Order");
        viewPOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPOButtonActionPerformed(evt);
            }
        });

        viewPRButton.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        viewPRButton.setText("View Purchase Requisition");
        viewPRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPRButtonActionPerformed(evt);
            }
        });

        ManageUserButton.setFont(new java.awt.Font("Bodoni MT", 0, 16)); // NOI18N
        ManageUserButton.setText("Manage User Account");
        ManageUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserButtonActionPerformed(evt);
            }
        });

        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 36)); // NOI18N
        jLabel1.setText("Admin - Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogOutButton)
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewAccButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManageUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewPRButton, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(viewPOButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewSaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewSupplierButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogOutButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(viewPRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RegisterUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(ManageUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(viewAccButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(viewPOButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(viewSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(viewItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(viewSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUserActionPerformed
        Register_GUI registerGUI = new Register_GUI(admin);
        registerGUI.show();
        dispose();
    }//GEN-LAST:event_RegisterUserActionPerformed

    private void viewSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSaleButtonActionPerformed
        ViewSales_GUI viewSalesGUI = new ViewSales_GUI(admin);
        viewSalesGUI.show();
        dispose();
    }//GEN-LAST:event_viewSaleButtonActionPerformed

    private void ManageUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserButtonActionPerformed
        ManageUser_GUI manageUserGUI = new ManageUser_GUI(admin);
        manageUserGUI.show();
        dispose();
    }//GEN-LAST:event_ManageUserButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        Login_GUI loginGUI = new Login_GUI();
        loginGUI.show();
        dispose();    
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void viewAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAccButtonActionPerformed
        EditUser_GUI editUserGUI = new EditUser_GUI(admin);
        editUserGUI.show();
        dispose();
    }//GEN-LAST:event_viewAccButtonActionPerformed

    private void viewItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemButtonActionPerformed
        ManageItem_GUI manageItemGUI = new ManageItem_GUI(admin);
        manageItemGUI.show();
        dispose();
    }//GEN-LAST:event_viewItemButtonActionPerformed

    private void viewPRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPRButtonActionPerformed
        ManagePR_GUI managePRGUI = new ManagePR_GUI(admin);
        managePRGUI.show();
        dispose();
    }//GEN-LAST:event_viewPRButtonActionPerformed

    private void viewPOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPOButtonActionPerformed
        ViewPO_GUI viewPOGUI = new ViewPO_GUI(admin);
        viewPOGUI.show();
        dispose();
    }//GEN-LAST:event_viewPOButtonActionPerformed

    private void viewSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupplierButtonActionPerformed
        ManageSupplier_GUI manageSupplierGUI = new ManageSupplier_GUI(admin);
        manageSupplierGUI.show();
        dispose();
    }//GEN-LAST:event_viewSupplierButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Admin_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton ManageUserButton;
    private javax.swing.JButton RegisterUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewAccButton;
    private javax.swing.JButton viewItemButton;
    private javax.swing.JButton viewPOButton;
    private javax.swing.JButton viewPRButton;
    private javax.swing.JButton viewSaleButton;
    private javax.swing.JButton viewSupplierButton;
    // End of variables declaration//GEN-END:variables
}
